name: Lore Origins update

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  linux-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.4
      - run: |
          haxe -version
          haxelib install hxnodejs
          haxelib setup ~/haxelib
      - name: Install hxcpp 4.3.2
        run: |
          haxelib install hxcpp 4.3.2
      - name: Install lime 8.2.2
        run: |
          haxelib install lime 8.2.2
      - name: Install openfl 9.4.1
        run: |
          haxelib install openfl 9.4.1
      - name: Install and Setup flixel 6.1.0
        run: |
          haxelib --never install flixel 6.1.0
          haxelib run lime setup flixel
          haxelib run lime setup
      - name: Install hxCodec 3.0.2
        run: |
          haxelib install hxCodec 3.0.2
      - name: Install flixel tools and others
        run: |
          haxelib install flixel-tools 1.5.1
          haxelib set flixel-tools 1.5.1
          haxelib install flixel-ui 2.6.3
          haxelib set flixel-ui 2.6.3
          haxelib install flixel-addons 3.3.2
          haxelib set flixel-addons 3.3.2
      - name: Install VLC Libraries and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libvlc-dev vlc-bin vlc-plugin-base libvlccore-dev
      - name: Install hxvlc 2.2.1
        run: |
          haxelib install hxvlc 2.2.1
      - name: Install hscript 2.5.0
        run: |
          haxelib install hscript 2.5.0
          haxelib set hscript 2.5.0
      - name: Install other libraries
        run: |
          haxelib install --quiet hxdiscord_rpc 1.2.4
      - name: List Installed Haxelibs
        run: haxelib list
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build Project.xml linux --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-release
          path: 'export/release/linux/bin'
  windows-release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.4
      - name: Setup Haxelib
        run: |
          haxelib install hxnodejs
          haxelib setup C:\haxelib
        shell: cmd
      - name: Install hxcpp 4.3.2
        run: |
          haxelib install hxcpp 4.3.2
        shell: cmd
      - name: Install lime 8.2.2
        run: |
          haxelib install lime 8.2.2
        shell: cmd
      - name: Install openfl 9.4.1
        run: |
          haxelib install openfl 9.4.1
        shell: cmd
      - name: Install and Setup flixel 6.1.0
        run: |
          haxelib --never install flixel 6.1.0
          haxelib run lime setup flixel
          haxelib run lime setup
        shell: cmd
      - name: Install flixel tools and others
        run: |
          haxelib install flixel-tools 1.5.1
          haxelib set flixel-tools 1.5.1
          haxelib install flixel-ui 2.6.3
          haxelib set flixel-ui 2.6.3
          haxelib install flixel-addons 3.3.2
          haxelib set flixel-addons 3.3.2
        shell: cmd
      - name: Install hxCodec 3.0.2
        run: |
          haxelib install hxCodec 3.0.2
        shell: cmd
      - name: Install VLC (Windows)
        run: |
          choco install vlc
        shell: cmd
      - name: Install hxvlc 2.2.1
        run: |
          haxelib install hxvlc 2.2.1
        shell: cmd
      - name: Install hscript 2.5.0
        run: |
          haxelib install hscript 2.5.0
          haxelib set hscript 2.5.0
        shell: cmd
      - name: Install other libraries
        run: |
          haxelib install --quiet hxdiscord_rpc 1.2.4
        shell: cmd
      - name: List Installed Haxelibs
        run: haxelib list
        shell: cmd
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build windows --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: export/release/windows/bin
  mac-release:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4
      - uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.4
      - run: |
          haxe -version
          haxelib install hxnodejs
          haxelib setup ~/haxelib
      - name: Install hxcpp 4.3.2
        run: |
          haxelib install hxcpp 4.3.2
      - name: Install lime 8.2.2
        run: |
          haxelib install lime 8.2.2
      - name: Install openfl 9.4.1
        run: |
          haxelib install openfl 9.4.1
      - name: Install and Setup flixel 6.1.0
        run: |
          haxelib --never install flixel 6.1.0
          haxelib run lime setup flixel
          haxelib run lime setup
      - name: Install flixel tools and others
        run: |
          haxelib install flixel-tools 1.5.1
          haxelib set flixel-tools 1.5.1
          haxelib install flixel-ui 2.6.3
          haxelib set flixel-ui 2.6.3
          haxelib install flixel-addons 3.3.2
          haxelib set flixel-addons 3.3.2
      - name: Install hxCodec 3.0.2
        run: |
          haxelib install hxCodec 3.0.2
      - name: Install VLC (macOS)
        run: |
          brew install vlc
          mkdir -p /Users/runner/haxelib/hxCodec/3,0,2/project/vlc/dll/MacOS/lib/
          ln -sf /opt/homebrew/lib/libvlc.dylib /Users/runner/haxelib/hxCodec/3,0,2/project/vlc/dll/MacOS/lib/libvlc.dylib || true
          ln -sf /opt/homebrew/lib/libvlccore.dylib /Users/runner/haxelib/hxCodec/3,0,2/project/vlc/dll/MacOS/lib/libvlccore.dylib || true
          ln -sf /usr/local/lib/libvlc.dylib /Users/runner/haxelib/hxCodec/3,0,2/project/vlc/dll/MacOS/lib/libvlc.dylib || true
          ln -sf /usr/local/lib/libvlccore.dylib /Users/runner/haxelib/hxCodec/3,0,2/project/vlc/dll/MacOS/lib/libvlccore.dylib || true
      - name: Install hxvlc 2.2.1
        run: |
          haxelib install hxvlc 2.2.1
      - name: Install hscript 2.5.0
        run: |
          haxelib install hscript 2.5.0
          haxelib set hscript 2.5.0
      - name: Install other libraries
        run: |
          haxelib install --quiet hxdiscord_rpc 1.2.4
      - name: List Installed Haxelibs
        run: haxelib list
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build mac --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac-release
          path: export/release/macos/bin
